coresight: Make all the placeholder functions static inline
Otherwise they may conflict with each other, giving issues like this:

ld.lld: error: duplicate symbol: coresight_disable_all_source_link
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

ld.lld: error: duplicate symbol: coresight_enable_all_source_link
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

ld.lld: error: duplicate symbol: coresight_claim_device_unlocked
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

ld.lld: error: duplicate symbol: coresight_claim_device
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

ld.lld: error: duplicate symbol: coresight_disclaim_device
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

ld.lld: error: duplicate symbol: coresight_disclaim_device_unlocked
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

ld.lld: error: duplicate symbol: coresight_loses_context_with_cpu
>>> defined in built-in.a(drivers/gpu/msm/adreno_coresight.o)
>>> defined in built-in.a(drivers/esoc/esoc-mdm-4x.o)

Signed-off-by: LibXZR <i@xzr.moe>

(cherry picked from libxzr/android_kernel_oneplus_sm8250 commit 7c5cc19c11e26be394960c09b9a7755656e0af77)
Original-author: LibXZR <i@xzr.moe>

Signed-off-by: TropsPk <TropsPk@users.noreply.github.com>